### ISSUE TITLE
Seed scraped realtor data to mongo

### ISSUE THREAD

**Issue by ErnestGaisie** [Lambton-AI-Group/house_price_prediction_project#21]

**Comment by ridhamm** [comment]
[move_data_from_csv_to_mongodb.txt](https://github.com/user-attachments/files/17630422/move_data_from_csv_to_mongodb.txt)
Thisa code moves data from csv file to MongoDB database

**Comment by ErnestGaisie** [comment]
Kindly create a new branch and make a PR to close the issue/task
