### ISSUE TITLE
Seed scraped zoho data to mongo

### ISSUE THREAD

**Issue by ErnestGaisie** [Lambton-AI-Group/house_price_prediction_project#22]

**Comment by Patelhet1512** [comment]
[move_zolodata_from_csv_to_mongodb.txt](https://github.com/user-attachments/files/17630765/move_zolodata_from_csv_to_mongodb.txt)

This code moves zolo data from csv file to MongoDB database.

**Comment by ErnestGaisie** [comment]
Kindly create a new branch and make a PR to close the issue/task
